POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "Learning Node.js and Express is really fun!",
    "important": true
}

###

POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "MongoDB makes persisting data easy and flexible",
    "important": false
}